### ISSUE TITLE
Problemas de dependência na fabapp

### ISSUE THREAD

**Issue by rodrigoreal** [simonfan/comparator#1]
Simon, posso te pedir pra voltar a branch master no commit [e8d263e5b409e758f5d8afed5191c887f4f4120b](https://github.com/simonfan/comparator/commit/e8d263e5b409e758f5d8afed5191c887f4f4120b)?
Porq essas alterações que você fez quebrou o portal (fabapp), eu até ia fazer um fork, mas esse projeto é dependência de outros projetos, dai eu iria precisar fazer dos outros tbm, e o buraco seria mais em baixo.

E vou pedir pra tomar cuidado nesses aqui tbm:
```
"https://github.com/simonfan/_q.git"
"https://github.com/simonfan/archetypo.git"
"https://github.com/simonfan/backbone.collection.lazy.git"
"https://github.com/simonfan/backbone.collection.multisort.git"
"https://github.com/simonfan/backbone.collection.queryable.git"
"https://github.com/simonfan/bb-dock.git"
"https://github.com/simonfan/bb-form.git"
"https://github.com/simonfan/bb-model-view.git"
"https://github.com/simonfan/bb-rendered-view.git"
"https://github.com/simonfan/bbdv.git"
"https://github.com/simonfan/comparator.git"
"https://github.com/simonfan/containers.git"
"https://github.com/simonfan/database.git"
"https://github.com/simonfan/deep.git"
"https://github.com/simonfan/dock.git"
"https://github.com/simonfan/improved-model.git"
"https://github.com/simonfan/jquery-meta-data.git"
"https://github.com/simonfan/jquery-selector-data-prefix.git"
"https://github.com/simonfan/jquery-value.git"
"https://github.com/simonfan/lowercase-backbone.git"
"https://github.com/simonfan/object-query.git"
"https://github.com/simonfan/pipe.git"
"https://github.com/simonfan/route-swtcher.git"
"https://github.com/simonfan/scope.git"
"https://github.com/simonfan/stateful-view.git"
"https://github.com/simonfan/subject.git"
"https://github.com/simonfan/swtch.git"
```

**Comment by simonfan** [comment]
Fala @rodrigoreal ! Tudo bem? Desculpas pelo inconveniente! Tinha conversado brevemente no passado sobre essas alterações com o Leo (acredito que vocês até tenham um fork), mas realmente seria muito risco alterar! O código que está nestes repositórios vai ficar congelado a partir de agora!

Reverti as alterações que tinha feito e movi a nova versão pra um fork. 

Outro repositório que eu alterei recentemente foi o "https://github.com/simonfan/object-query.git", mas já fiz o mesmo processo de reverter.

Acredito que esteja tudo certo agora, por favor me avise! Vou deixar a issue aberta até que você consiga testar :)

Obrigado!

**Comment by rodrigoreal** [comment]
Muito obrigado @simonfan, parece que está tudo funcionando normalmente agora.

**Comment by simonfan** [comment]
Uhul! :)
